version: "3.9"
services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker-volumes/mongo:/data/db
    # For the development we can use username and password but for now we don't need that 
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: "root"
    #   MONGO_INITDB_ROOT_PASSWORD: "example"
  mysql:
    container_name: mysql_container
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=jeral
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=jobber_auth_db
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jeral
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=jobber_reviews_db
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql